### ISSUE TITLE
I can't validate form with multi array names

### ISSUE THREAD

**Issue by maciekwyka** [jquery-validation/jquery-validation#2310] opened 2020-01-09 14:47 UTC
### Subject of the issue
I have form where user can dynamically add or remove rows, names of input files is for example "colorkeeper_project[rooms_attributes][][surfaces_attributes][][name]"
I have no idea how to deal with it, when I make rule for "colorkeeper_project[rooms_attributes][][surfaces_attributes][][name]" only the first row is validating.

### Your environment
* version of `jquery-validate`: 1.16.0
* which browser and its version: Safari 13.0.4

**Comment by s-fraser2007** [comment] 2020-02-03 13:37
Hi, I was having this same issue, I came accross this
http://www.codeboss.in/web-funda/2009/05/27/jquery-validation-for-array-of-input-elements/
Works nicely

**Comment by thejoker-dev** [comment] 2020-04-29 18:18
Using jquery validate 1.19.1 and modifying the jquery.validate.js file on line 465, replacing with this function should be fine.

`checkForm: function() {
            this.prepareForm();
            for ( var i = 0, elements = (this.currentElements = this.elements()); elements[i]; i++ ) {
                var checkingElements = this.findByName( elements[i].name ).not(this.settings.ignore);
                if (checkingElements.length !== undefined && checkingElements.length > 1) {
                    for (var cnt = 0; cnt < checkingElements.length; cnt++) {
                        this.check( checkingElements[cnt] );
                    }
                } else {
                    this.check( elements[i] );
                }
            }
            return this.valid();
        },`

I hope to be of help ;)

**Comment by bytestream** [comment] 2020-06-19 11:54
Duplicate of https://github.com/jquery-validation/jquery-validation/issues/2326#issuecomment-646594251 which has better reproducer and description of issue.

Suggest to close.

**Closed** 2022-04-30 09:24 UTC
