### ISSUE TITLE
1.18.0 fails in Internet Explorer 11

### ISSUE THREAD

**Issue by eobrien-fsp** [jquery-validation/jquery-validation#2225] opened 2018-10-13 00:01 UTC
### Subject of the issue
Validation fails in Internet Explorer 11

### Your environment
jQuery Validate v1.18.0
Internet Explorer 11

### Steps to reproduce
```
<form id="RegistrationForm">
<input type="text" id="FirstName" name="FirstName"/>
<input type="submit" value="Submit"/>
</form>

<script type="text/javascript">

    jQuery('#RegistrationForm').validate({
        ignore: ".ignore",
        rules: {
            FirstName: {
                required: true
            }
        }
    });

</script>
```

### Expected behaviour
Not valid status should be removed from "required" fields after content is entered.

### Actual behaviour
Fields stay in the not valid status even after content is entered. The form cannot be submitted.

**Comment by staabm** [comment] 2018-10-13 08:18
I guess this is a duplicate of https://github.com/jquery-validation/jquery-validation/issues/2211

**Comment by Arkni** [comment] 2018-10-13 22:31
Duplicate of #2211

**Closed by Arkni** 2018-10-13 22:31 UTC
