### ISSUE TITLE
It fails with an error when there is a summernote rich text widget in a form to be validated

### ISSUE THREAD

**Issue by vporton** [jquery-validation/jquery-validation#2338] opened 2020-07-26 13:49 UTC

**Comment by vporton** [comment] 2020-07-26 14:18
The same bug with jQuery WYSIWYG Rich Text Editor Plugin - Froala Editor.

**Comment by KoalaBear84** [comment] 2021-11-29 14:44
Probably a duplicate of #3019 which is now solved by the merge of #2154

**Closed** 2021-11-29 20:17 UTC
