### ISSUE TITLE
Not working with Jquery v1.12.4

### ISSUE THREAD

**Issue by landman** [jquery-validation/jquery-validation#2099] opened 2017-10-28 13:34 UTC
I have a lot errors.

"jquery.validate.js:77 Uncaught TypeError: Cannot read property 'msie' of undefined"

"Uncaught TypeError: Cannot read property 'settings' of undefined"

**Comment by Arkni** [comment] 2017-10-28 16:27
Please provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) containing a set of reproducible steps.

**Comment by Arkni** [comment] 2018-03-12 22:37
Hey there!

I'm closing this issue since the original poster hasn't yet responded to the request made to them 4 months ago. I therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if you have followup question, let us know with a comment and I'll be happy to reopen the issue.

Thanks!

**Closed by Arkni** 2018-03-12 22:37 UTC
Labels: NO FIDDLE/REPRO
