### ISSUE TITLE
validation is not working with the textarea ?

### ISSUE THREAD

**Issue by vishwakarmanikhil** [jquery-validation/jquery-validation#2368] opened 2020-12-17 16:22 UTC
I am facing this issue.
I am using the rich text editor ckeditor5. I have defines rules as required and minlength to textarea but it is not working. can you please let me know if this query is already answered or still this is an isssue.

_Originally posted by @vishwakarmanikhil in https://github.com/jquery-validation/jquery-validation/issues/2137#issuecomment-747546013_

**Comment by RobJohnston** [comment] 2020-12-18 01:17
From my brief searching, I think that the problem is that CKEditor changes the `textarea` to hidden, and jQuery Validation doesn't validate hidden fields.

I found a similar question on StackOverflow and the respondents provide various solutions:  https://stackoverflow.com/questions/22248918/jquery-validation-not-working-with-ckeditor

**Comment by vishwakarmanikhil** [comment] 2020-12-18 06:12
thank you @RobJohnston I found the correct solution.

**Comment by RobJohnston** [comment] 2020-12-18 22:25
For posterity, I will note that this relates to #1944, #1718, and #1298.

If you're satisfied, can you close this issue @vishwakarmanikhil ?

**Closed** 2020-12-18 22:34 UTC
