### ISSUE TITLE
Demo pages no longer work

### ISSUE THREAD

**Issue by kingmotley** [jquery-validation/jquery-validation#1894] opened 2016-11-17 18:36 UTC
### Your environment
* Chrome version Version 54.0.2840.99 m (64-bit)

### Steps to reproduce

1. Go to https://jqueryvalidation.org/files/demo/milk/
2. Click submit

Also

1. Go to https://jqueryvalidation.org/files/demo/multipart/
2. Click Next

### Expected behaviour
Validation message to appear

Also

Only step to appear at time until next is clicked, and validations to appear.

### Actual behaviour
No validations appear, page refreshes

Also

All 3 steps appear, and clicking next or submit does nothing.

**Comment by kylefox** [comment] 2017-02-10 15:43
Looks like a duplicate of #1939.

**Comment by staabm** [comment] 2017-04-13 15:16
#1939  was closed and fixed. demos are available again. thx for noticing.

**Closed by staabm** 2017-04-13 15:16 UTC

**Comment by feralreason** [comment] 2017-04-13 17:33
Thanks for the notification.  I checked this URL though: https://jqueryvalidation.org/files/demo/milk/  and even after clearing history and refreshing I'm not seeing any validation messages.  Did you fix this one too?


I love jquery validation. We're using it extensively on a private sales tools site.  (Did you recently switch to SSL? Could it be trying to load an http URL from somewhere?)


Thanks,
     Glenn


Glenn Ferrell, PMP
Web Development, SEO
gfWEBsoft LLC  
glenn@gfwebsoft.com


630-469-9779
630-670-0342(C)



-----Original Message-----

**Comment by Arkni** [comment] 2017-04-13 18:08
@feralreason 
See https://github.com/jquery-validation/jquery-validation/issues/1939#issuecomment-293938178
