### ISSUE TITLE
How to force localization for a specific language?

### ISSUE THREAD

**Issue by sowinski** [jquery-validation/jquery-validation#1952] opened 2017-02-16 11:48 UTC
### Subject of the issue
I would like to enable localization in german ('de'). But it's not working. I already included "messages_de.js" and "methods_de.js". (My browser settings are in English)

If I validate an numeric field, I got an error for "12,12" if I type "12.12" everything is fine => No validation error. 

My validation errors are in German. This is working at least.

I also initialize validate with { ... lang: 'de', ... } 

### Your environment
jQuery Validation Plugin v1.15.0
Firefox 50.1.10

### Expected behaviour
Validation of "12,12" should be accepted instead of "12.12"

### Actual behaviour
Decimal values with "." are accepted instead of ","

**Comment by Arkni** [comment] 2017-02-16 12:25
Did you import the file `methods_de.js` before or after importing `jquery.validate.js` ?
Also, there is no such option as `lang` for this plugin. Where did you find it ?

**Comment by sowinski** [comment] 2017-02-16 13:01
> Did you import the file methods_de.js before or after importing jquery.validate.js ?
After, is this correct? 

> Also, there is no such option as lang for this plugin. Where did you find it

Found it somewhere on stackoverflow.

**Comment by Arkni** [comment] 2017-02-16 13:14
After is correct.

> Also, there is no such option as lang for this plugin. Where did you find it
>> Found it somewhere on stackoverflow.

Please refer to [`validate()'s docs`](https://jqueryvalidation.org/validate/) whenever you need to know which options are supported and which are not.

Can you provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) ? I will look into it when I have some free time.

Thanks!

**Comment by sowinski** [comment] 2017-02-16 13:48
I found my problem. It is not possible to use number and min within one rule:
https://jsfiddle.net/k1L5aaar/5/

If you type in "12.12" or "12,12" you get always an error. At the beginning I thought it's a localization problem, but its not. Is this a bug?

Thank you!

**Comment by Arkni** [comment] 2017-02-17 11:24
For your case:
* `12.12` will fail for `number` validator which check that after a period `.` there should be exactly 3 digits. This only true for .
* `12,12` will fail for `min` validator, because the `min` will only check that the value is greater than the param you passed to it (1 in your case).
As you used a `text` input, the plugin will receive a string value (`"12,12"`). And `"12,12" >= 1` will return `false` due to `JavaScript` try to coerce `"12,12"` to number which leads to `NaN` as it's not a valid number that can be directly parsed using the `Number` contructor.

> Is this a bug?

No, it's not a bug, it's the expected behaviour. Also, the `number`, `min` and `max` methods are not locale aware. So you have to make a custom rule for validating numbers according to `de` local. Something like this should suffice:
```js
$.validator.addMethod("deNumbers", function(value, element, param) {
  var isValid = $.validator.methods.number.call(this, value, element, param);
  
  // If the number is valid according to `de` local, we then have to check
  // the `min` method
  if (isValid) {
    var number = Number(value.replace(/\./g, "").replace(/\,/, "."));

    // Set the min error message
    $.validator.messages.deNumbers = $.validator.messages.min(param);
    return $.validator.methods.min.call(this, number, element, param);
  }

  // Set the number error message
  $.validator.messages.deNumbers = $.validator.messages.number;

  return isValid;
}, $.validator.messages.deNumbers);
```

**Comment by Arkni** [comment] 2017-02-17 11:26
I'll close this for now, but feel free to ask if you have followup questions.

**Closed by Arkni** 2017-02-17 11:26 UTC
