### ISSUE TITLE
type undefined crashing javascript when a form field within an array of input fields, one of which is visible, is hidden

### ISSUE THREAD

**Issue by javismiles** [jquery-validation/jquery-validation#1962] opened 2017-02-24 20:26 UTC
Good day,

I have a form with a bunch of hidden link[] array fields.  It's an array of input fields.
They all have display none.

The rule is:

"links[]": {
		required: false,
		maxlength: 6
},

I have the latest version of your plugin.

Then I make one of them visible. So for example link[1] becomes visible. The rest are still hidden.

The validator crashes javascript with a type unknown of undefined because it tries to process the hidden fields.

and "element" variable is undefined in them.

What is happening is that when all the fields are hidden then it's ok, your plugin ignores them.
But If i show one of them...  one of the link[] fields, then it tries to process them all, the visible and the invisible, and that's where the problem happens.

So I may have 4 fields, and in one of those link[] is visible, but in the other 3 link[] input is hidden.
And your plugin will try to process the 4 of them just because one of them is visible.

What can I do, or what I can I change in your code to either:

- ignore the field if "element" is undefined
- or much better, just ignore any field that has display:none, that is hidden

The problem here is that link[] is an array of input fields,

and link[1] may be visible but link[2], link[3] etc are hidden

but your plugin, just because link[1] is visible, tries to also process link[2] etc, the hidden ones,
and the whole thing crashes,

please tell me a temporary solution that I can put in your code to prevent this from happening

thanks a lot

**Comment by Arkni** [comment] 2017-02-24 20:40
Please provide a [JSFiddle](https://jsfiddle.net/) or [JSBin](https://jsbin.com/) containing a set of reproducible steps.

**Comment by Arkni** [comment] 2017-04-06 16:24
Hey there!

I'm closing this issue since the original poster hasn't yet responded to the question or request made to them ~2 months ago. I therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if you have followup question, let us know with a comment and I'll be happy to reopen the issue.

Thanks!

**Closed by Arkni** 2017-04-06 16:24 UTC
Labels: NO FIDDLE
