### ISSUE TITLE
Issue with v1.18.0, IE and Required

### ISSUE THREAD

**Issue by phenry2** [jquery-validation/jquery-validation#2217] opened 2018-09-26 06:07 UTC
### Summary of Issue
Since upgrading to v1.18.0, text boxes trigger a required validation error even though there is text in the text box. It does not happen in chrome. Rolling back to v1.17.0 fixed the issue.

### Your environment
* version of `jquery-validate`: v1.18.0
* which browser and its version: Internet Explorer v11

### Steps to reproduce
Simple MVC Core 2.1 application with a text box created using Html.TextBoxFor.  The input element is generated with data-val="true".  Html.ValidationFor used to generate the validation error.

### Expected behaviour
Would expect no validation error when submit clicked. Normally then when typing in the field, the validation error cleared.

### Actual behaviour
Validation error persists and cannot submit form.

Extra debugging revealed that when jquery-validate checked if the element was editable (isContentEditable), it then either did val = $element.text() or val = $element.val(). In the case of my text box, the isContentEditable flag was true, get $element.text() returned "".  Hence the required validation failed. $element.val() return the actual contents of the textbox, but this was not used.

**Comment by Worthy7** [comment] 2018-09-26 06:56
Could perhaps be in https://github.com/jquery-validation/jquery-validation/pull/2053

**Comment by Worthy7** [comment] 2018-09-26 07:04
Just a note to whoever fixes this - please add a proper failing `Required` test if possible on this fix.

**Comment by Worthy7** [comment] 2018-09-26 07:05
(This is actually a massive bug, it will nuke all forms with `Required`, quick patch for NPM?)

**Comment by vijay18-91** [comment] 2018-09-26 07:13
More details - The 'Required' functions 3rd parameter - param is always undefined even if the parameters are added while adding new validation methods which then called 'Depend' function with param and elements and returns "dependency-mismatch" for IE11 browser.

**Comment by sytheveenje** [comment] 2018-09-26 08:44
Got the same issue, went back to `v1.17.0` and everything works again.

**Comment by Arkni** [comment] 2018-09-30 13:04
Duplicate of #2211

**Closed by Arkni** 2018-09-30 13:04 UTC
