### ISSUE TITLE
Input Tag Having Spaces (only) Validation Not Worked In Latest Version

### ISSUE THREAD

**Issue by sushilmaddy** [jquery-validation/jquery-validation#2027] opened 2017-07-08 11:16 UTC
As I mentioned above(title) , if we create an input tag with required =true and fill up input tag only with spaces and hit submit button, its not showing validate message, it validates the input tag in this case which is totally wrong.  
So I have figured out from older version that you have missed $.trim(value)
 methods: {

		// http://jqueryvalidation.org/required-method/
		required: function( value, element, param ) {
			// check if dependency is met
			if ( !this.depend( param, element ) ) {
				return "dependency-mismatch";
			}
			if ( element.nodeName.toLowerCase() === "select" ) {
				// could be an array for select-multiple or a string, both are fine this way
				var val = $( element ).val();
				return val && val.length > 0;
			}
			if ( this.checkable( element ) ) {
				return this.getLength( value, element ) > 0;
			}
			return $.trim( value ).length > 0; 0;**_
		},

**Comment by Arkni** [comment] 2017-07-08 11:29
Duplicate of #1886

**Closed by Arkni** 2017-07-08 11:29 UTC

**Comment by staabm** [comment] 2017-07-08 18:50
Maybe we should add a prominent note into the readme/upgrade/changelog @Arkni ?

**Comment by Arkni** [comment] 2017-07-09 17:35
Yeah, we should only add it to the section [Reporting issues and contributing code](https://github.com/jquery-validation/jquery-validation#reporting-issues-and-contributing-code) as it's already mentioned in the changelog of [`v1.14.0`](https://github.com/jquery-validation/jquery-validation/releases/tag/1.14.0).

**Comment by Arkni** [comment] 2017-07-09 18:59
@staabm 
See #2028
