### ISSUE TITLE
require_from_group disables all other validations.

### ISSUE THREAD

**Issue by smaudet** [jquery-validation/jquery-validation#1865] opened 2016-09-21 19:33 UTC
### Checklist for this issue

Use the default require_from_group in additional-methods
Observe that all other validations are ignored
Also observe that validations in general seem to be broken.
### Subject of the issue

require_from_group should not be non-functional
### Your environment
- version of `jquery-validate`: 1.15.1
- Browser and its version: Google Chrome 51

Note that the fix found in the original bug:
https://github.com/jzaefferer/jquery-validation/issues/412

Seems to fix this bug.

This seems to be a regression.

**Comment by staabm** [comment] 2016-12-01 16:03
would be great if you could provide a unit test which fails with 1.15.1 but succeeds on a previous version, so we can test this specific regression.

**Comment by Arkni** [comment] 2018-03-12 23:08
Hey there!

I'm closing this issue since the original poster hasn't yet responded to the request made to them a long time ago. I therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if you have followup question, let us know with a comment and I'll be happy to reopen the issue.

Thanks!

**Closed by Arkni** 2018-03-12 23:08 UTC
Labels: NO FIDDLE/REPRO
