### ISSUE TITLE
Pattern Additional Method Issue

### ISSUE THREAD

**Issue by dpDesignz** [jquery-validation/jquery-validation#2299] opened 2019-08-30 03:15 UTC
### Subject of the issue
Additional method pattern not working as expected. Returns false for expression

### Your environment
* version of `jquery-validate`: 1.19.1
* which browser and its version: Firefox 70.0b1 (64-bit)

### Steps to reproduce
```javascript
$.validator.addMethod( "pattern", function( value, element, param ) {
    if ( this.optional( element ) ) {
        return true;
    }
    if ( typeof param === "string" ) {
        param = new RegExp( "^(?:" + param + ")$" );
    }
    return param.test( value );
}, "Invalid format." );
```

``` javascript
$().ready(function() {
  $("#admin-new-password-form").validate({
    rules: {
      password: {
        required: true,
        minlength: 6,
        maxlength: 64,
        pattern: "/((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\W]).{6,64})/"
      }
    },
    messages: {
      password: {
        required: "Please enter your new password",
        minlength: "Please enter at least 6 characters",
        maxlength: "Please enter no more than 64 characters",
        pattern: "Please enter a valid password"
      }
    }
  });
});
```

### Expected behaviour
Return true if enter in a password has at least 1 number, 1 lower case, 1 uppercase, and 1 character. 
Example that should match: `lu123LU@1`

### Actual behaviour
Returns False

I have just had [a discussion at length on SO](https://stackoverflow.com/questions/57719216/javascript-regexp-password-validation-with-jqueryvalidation). I'm not sure if I've just misunderstood it completely, but I've posted an answer of how I had to fix it. I'm not sure if it's something that can be rectified or not? Or if the docs just need more details.

**Comment by Arkni** [comment] 2019-09-01 14:30
Hi @dpDesignz,

Your issue has nothing to do with the plugin. The pattern you pass to `pattern` method is wrong and you should remove the leading and trailing slashes from your pattern.

```diff
    rules: {
      password: {
        required: true,
        minlength: 6,
        maxlength: 64,
-        pattern: "/((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\W]).{6,64})/"
+        pattern: "((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\W]).{6,64})"
      }
    }
```

or you can pass a regex instead of a string:

```diff
    rules: {
      password: {
        required: true,
        minlength: 6,
        maxlength: 64,
-        pattern: "/((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\W]).{6,64})/"
+        pattern: /((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\W]).{6,64})/
      }
    }
```

I'm going to close this issue. Please feel free to comment if you have followup questions.

Thanks!

**Closed by Arkni** 2019-09-01 14:30 UTC

**Comment by dpDesignz** [comment] 2019-09-01 22:24
Hi Arkni. Thanks for commenting. I tried both of those methods but they caused my javascript to stop triggering and I got error messages in my console saying the validator method wasn't defined. :(

**Comment by Arkni** [comment] 2019-09-02 00:00
Hi @dpDesignz,

I just checked and I think the issue is you didn't escape the `\` in your string too, otherwise it will be dropped as it wasn't there because the caracter follwing it is not something special (`"`, ...).

This should work just fine:

```diff
    rules: {
      password: {
        required: true,
        minlength: 6,
        maxlength: 64,
-       pattern: "/((?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\W]).{6,64})/"
        // It will act as if your used `String.raw`
+       pattern: "((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\\W]).{6,64})"
      }
    }
```

Also, the other version of passing a RegEx directly should work as expected. And as far as I can tell, the error you shared means that the `pattern` method wasn't defined as in the block of code that add it was not run (I guess due to a Syntax error or something like that).

**Comment by dpDesignz** [comment] 2019-09-02 00:15
@Arkni that's it! Thank you so much. Don't you hate it when it's obvious and you just miss it? 😄
