### ISSUE TITLE
Required validation failed on IE 11

### ISSUE THREAD

**Issue by SeriaWei** [jquery-validation/jquery-validation#2233] opened 2018-10-31 02:40 UTC
**After update the version to 1.18, I found the required validation is not work on IE 11.**

I did some debug and found `isContentEditable` always `true` on IE11 

```
<input type="text" id="userName" name="userName" class="form-control" data-val="true" data-val-required="Please input your name">
```
### Debug info
![image](https://user-images.githubusercontent.com/6006218/47762757-ea8e6200-dcf8-11e8-9c5a-65fcabbcf3e9.png)

the $element has value
![image](https://user-images.githubusercontent.com/6006218/47762798-0abe2100-dcf9-11e8-9520-b0065efe2998.png)

**I found 'isContentEditable' is from this commit:**
https://github.com/jquery-validation/jquery-validation/commit/7c22d68a4b906498f7d1b76a5751135f0d8266a6

**Comment by wjstraver** [comment] 2018-10-31 10:44
Got a similar bug on IE11: input fields with required still get the error message "this field is required" while they are filled in. However, it did work when the field was already prefilled. Seems like something goes wrong with the onchange....

Tested on Windows 7, Windows 8.1 and Windows 10 with IE11.

Input field looks as follows:
`<input class="form-control" type="email" id="email" name="email" value required="required">`

**Comment by markhowellsmead** [comment] 2018-11-02 15:14
+1

**Comment by Arkni** [comment] 2018-11-04 15:20
Duplicate of #2211

**Closed by Arkni** 2018-11-04 15:20 UTC

**Comment by staabm** [comment] 2018-11-28 18:46
just published 1.19.0 with a fix for this issue.

sorry the any inconvenience this bug has caused for you guys.

**Comment by markhowellsmead** [comment] 2018-11-29 08:48
Thanks @staabm!

**Comment by wjstraver** [comment] 2018-11-29 09:10
Had the package locked on 1.17.0 for now, will checkout 1.19.0 later today.

Thanks for the update @staabm !

**Comment by waikchiu5** [comment] 2018-12-17 10:14
Hi All
Any workaround on this?
I add some custom validation method by addMethod.

I found totally different result between IE11 and chrome.
In IE11
```
addMethod("add",function(value,element,param){
//value always is empty.
//$(element).val() can get the value
});
```

However, this code is passed in Chrome/edge/FF

**Comment by Arkni** [comment] 2018-12-17 11:45
Hi @wjstraver,

Please upgrade to version `1.19.0`, it contains the fix.

Thanks :)

**Comment by waikchiu5** [comment] 2018-12-18 02:15
@Arkni 
Thanks for you update. I am looking for the workaround. Since I can't upgrade the plugin by now. It related many many function.

**Comment by Arkni** [comment] 2018-12-18 22:59
Hi @waikchiu5,

The only workaround I can think of right now, is by overriding the internal method `elementValue` to use the new implementation that contains the fix. Although I don't recommend it myself, but as the situation is a little complicated for you, you can do so as follows:

```js
var validator = $("your form selector").validate({ /* your options */ });

validator.elementValue = function( element ) {
  var $element = $( element ),
    type = element.type,
    isContentEditable = typeof $element.attr( "contenteditable" ) !== "undefined" && $element.attr( "contenteditable" ) !== "false",
    val, idx;

  if ( type === "radio" || type === "checkbox" ) {
    return this.findByName( element.name ).filter( ":checked" ).val();
  } else if ( type === "number" && typeof element.validity !== "undefined" ) {
    return element.validity.badInput ? "NaN" : $element.val();
  }

  if ( isContentEditable ) {
    val = $element.text();
  } else {
    val = $element.val();
  }

  if ( type === "file" ) {

    // Modern browser (chrome & safari)
    if ( val.substr( 0, 12 ) === "C:\\fakepath\\" ) {
      return val.substr( 12 );
    }

    // Legacy browsers
    // Unix-based path
    idx = val.lastIndexOf( "/" );
    if ( idx >= 0 ) {
      return val.substr( idx + 1 );
    }

    // Windows-based path
    idx = val.lastIndexOf( "\\" );
    if ( idx >= 0 ) {
      return val.substr( idx + 1 );
    }

    // Just the file name
    return val;
  }

  if ( typeof val === "string" ) {
    return val.replace( /\r/g, "" );
  }
  return val;
};
```

But, please next time you had a chance to upgrade, please do so and remove the override code.

Thanks :)

**Comment by waikchiu5** [comment] 2018-12-20 04:10
> Hi @waikchiu5,
> 
> The only workaround I can think of right now, is by overriding the internal method `elementValue` to use the new implementation that contains the fix. Although I don't recommend it myself, but as the situation is a little complicated for you, you can do so as follows:
> 
> ```js
> var validator = $("your form selector").validate({ /* your options */ });
> 
> validator.elementValue = function( element ) {
>   var $element = $( element ),
>     type = element.type,
>     isContentEditable = typeof $element.attr( "contenteditable" ) !== "undefined" && $element.attr( "contenteditable" ) !== "false",
>     val, idx;
> 
>   if ( type === "radio" || type === "checkbox" ) {
>     return this.findByName( element.name ).filter( ":checked" ).val();
>   } else if ( type === "number" && typeof element.validity !== "undefined" ) {
>     return element.validity.badInput ? "NaN" : $element.val();
>   }
> 
>   if ( isContentEditable ) {
>     val = $element.text();
>   } else {
>     val = $element.val();
>   }
> 
>   if ( type === "file" ) {
> 
>     // Modern browser (chrome & safari)
>     if ( val.substr( 0, 12 ) === "C:\\fakepath\\" ) {
>       return val.substr( 12 );
>     }
> 
>     // Legacy browsers
>     // Unix-based path
>     idx = val.lastIndexOf( "/" );
>     if ( idx >= 0 ) {
>       return val.substr( idx + 1 );
>     }
> 
>     // Windows-based path
>     idx = val.lastIndexOf( "\\" );
>     if ( idx >= 0 ) {
>       return val.substr( idx + 1 );
>     }
> 
>     // Just the file name
>     return val;
>   }
> 
>   if ( typeof val === "string" ) {
>     return val.replace( /\r/g, "" );
>   }
>   return val;
> };
> ```
> 
> But, please next time you had a chance to upgrade, please do so and remove the override code.
> 
> Thanks :)

@Arkni 

It works for me!
Thanks for your advise.
