### ISSUE TITLE
E-mail validation is not working properly

### ISSUE THREAD

**Issue by blaasvaer** [jquery-validation/jquery-validation#2160] opened 2018-04-06 14:23 UTC
And even the example on the site confirms it: https://jqueryvalidation.org/email-method/

Any plans on fixing this?

**Comment by MichaelPehl** [comment] 2018-04-06 17:51
how did you test exactly? how did it work before? what does not work now? what did you enter?

just saying "does not work" ... does not help. please provide more info.

**Comment by blaasvaer** [comment] 2018-04-06 20:33
Try to type in a e-mail. You'll see what I mean.

**Comment by RobJohnston** [comment] 2018-04-06 21:35
Duplicate of https://github.com/jquery-validation/jquery-validation/issues/2117.

**Comment by staabm** [comment] 2018-04-07 15:45
See the README.md for details.

> **IMPORTANT NOTE ABOUT EMAIL VALIDATION**. As of version 1.12.0 this plugin is using the same regular expression that the [HTML5 specification suggests for browsers to use](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address). We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider [using a custom method](http://jqueryvalidation.org/jQuery.validator.addMethod/).
In case you need to adjust the built-in validation regular expression patterns, please [follow the documentation](http://jqueryvalidation.org/jQuery.validator.methods/).

**Closed by staabm** 2018-04-07 15:45 UTC

**Comment by blaasvaer** [comment] 2018-04-10 11:01
So, instead of placing the information where it's relevant, we are sent on a wild-goose chase all over the web for at solution ... ending up here debating whether yadda@localhost is a valid e-mail, sigh!

For anyone else needing to validate a REAL e-mail in a REAL world scenario, add this to your validator:

```
$.validator.methods.email = function( value, element ) {
	return this.optional( element ) || /[a-z]+@[a-z]+\.[a-z]{2,}/.test( value );
}
```
I will validate this:

```
any_number_of_characters @ any_number_of_characters . min_2_characters
```
*NOTE: spaces only inserted for readability.*

**Comment by staabm** [comment] 2018-04-10 11:26
@blaasvaer how a valid email adress looks like depends on the application and the library itself can never provide a pattern which works for all of the library users.

therefore we provide the pattern which is defined by the W3C consortium and provide lots of information on how one can define a custom pattern.

not sure what we could do better.

maybe you could use the issue search next time and see one of the plenty email-duplicate-issues of your described problem,... that actually could help.

**Comment by blaasvaer** [comment] 2018-04-10 11:30
The problem with documentation often is, that the writer of the docs do not take into account where people come from when entering af doc page (could be from clicking around, from a search or what have you). And my point simply is: put the deviations where they belong. Not in some random README (which no one reads, remember). That's all I'm saying ...

And sorry, but this is just pure arrogance:
> not sure what we could do better.
