### ISSUE TITLE
$("#signupForm").validate is not a function. 

### ISSUE THREAD

**Issue by wimdemo** [jquery-validation/jquery-validation#1983] opened 2017-03-28 10:34 UTC
### Subject of the issue
I get a browser error: $("#signupForm").validate is not a function. (In '$("#signupForm").validate', '$("#signupForm").validate' is undefined)

### Your environment
* version 1.16

### Steps to reproduce
`<script type="text/javascript" src="/user/js/lib/jquery.js"></script>
            <script type="text/javascript" src="/user/js/dist/jquery.validate.min.js"></script>
            <script type="text/javascript">
               /* $.validator.setDefaults( {
                 submitHandler: function () {
                 alert( "submitted!" );
                 }
                 } );*/

                $(document).ready(function() {
                    $("#signupForm").validate({
                        rules: {
                            profileAddress: "required",
                            profilePostcode: "required",
                            profileGemeente: "required",
                            profielMobiel: "required",
                            profileNoodnr: "required",
                            profileLogin: {
                                required: true,
                                email: true
                            },
                            profileNewPassword: {
                                minlength: 6
                            },
                            profileNewPasswordRepeat: {
                                minlength: 6,
                                equalTo: "#profileNewPassword"
                            }
                        },
                        messages: {
                            profileAddress: "Dit is een verplicht item",
                            profilePostcode: "Dit is een verplicht item",
                            profileGemeente: "Dit is een verplicht item",
                            profielMobiel: "Dit is een verplicht item",
                            profileNoodnr: "Dit is een verplicht item",
                            profileLogin: {
                                required: "Gelieve een geldig e-mailadres in te geven",
                                email: "Gelieve een geldig e-mailadres in te geven"
                            },
                            profileNewPassword: {
                                minlength: "Het nieuwe paswoord moet mininum 6 tekens lang zijn"
                            },
                            profileNewPasswordRepeat: {
                                minlength: "Het nieuwe paswoord moet mininum 6 tekens lang zijn",
                                equalTo: "Gelieve hetzelfde paswoord als hierboven in te geven"
                            }
                        },
                        errorElement: "em",
                        errorPlacement: function ( error, element ) {
                            // Add the `help-block` class to the error element
                            error.addClass( "help-block" );

                            if ( element.prop( "type" ) === "checkbox" ) {
                                error.insertAfter( element.parent( "label" ) );
                            } else {
                                error.insertAfter( element );
                            }
                        },
                        highlight: function ( element, errorClass, validClass ) {
                            $( element ).parents( ".col-sm-5" ).addClass( "has-error" ).removeClass( "has-success" );
                        },
                        unhighlight: function (element, errorClass, validClass) {
                            $( element ).parents( ".col-sm-5" ).addClass( "has-success" ).removeClass( "has-error" );
                        }
                    } );

                });

            </script>`
### Expected behaviour
Validation is not working.

### Actual behaviour
The validation is not working

**Comment by rohittiwarirvt** [comment] 2017-04-03 05:30
Open Developer tools in browser, and check whether the library is loaded correctly without any errors like 404 not found for the file or else cdn version of the library `<script src="https://code.jquery.com/jquery-1.11.1.min.js"></script><script src="https://cdn.jsdelivr.net/jquery.validation/1.15.0/jquery.validate.min.js"></script>` in header.
Also check in browser console `jQuery.validator
` results in printing `function ( options, form ) {
	this.settings = $.extend( true, {}, $.validator.defaults, options );
	this.currentForm = form;
	this.init();
}`

**Comment by davidmerrique** [comment] 2017-04-04 15:22
@rohittiwarirvt It seems to be broken in jquery@^3.2.0. Works fine in 3.1.1

**Comment by staabm** [comment] 2017-04-04 15:25
do this errors also occur in jquery 3.2.1?

I dont believe that using the very same code but just changing jquery 3.2.x with 3.1.1 works... 
Also the jquery project itself states that
> There should be no compatibility issues if upgrading from jQuery 3.0+.

please provide a jsfiddle which proves that this code works on jquery 3.1.1 but not 3.2

**Comment by davidmerrique** [comment] 2017-04-04 16:16
@staabm False alarm on my end! My issue was only happening with Webpack and I fixed it by removing my node_modules and reinstalling. I think @wimdemo might be having a different problem though. Thanks.

**Comment by Arkni** [comment] 2018-03-12 22:39
Hey there!

I'm closing this issue since the original poster hasn't yet responded to the request made to them a year ago. I therefore assume that the user has lost interest or resolved the problem on their own.

Don't worry though; if you have followup question, let us know with a comment and I'll be happy to reopen the issue.

Thanks!

**Closed by Arkni** 2018-03-12 22:39 UTC
Labels: NO FIDDLE/REPRO

**Comment by AndrewSouthpaw** [comment] 2018-03-13 16:48
@Arkni so I just ran into this issue, and it appears that `yarn` doesn't play nicely with it. When I install through `npm i` there are no issues, but when I use `yarn` it results in the same issue. I can see it attaching `.validator` to the jquery object inside the dist file (if I `console.log` there), but outside in my `app.js` file it turns out `$.validator` is undefined. Has anyone else run into a similar issue?

**Comment by arnaud** [comment] 2018-03-15 14:41
@AndrewSouthpaw I'm in the exact same situation.

```
node: 9.7.1
yarn: 1.5.1
npm: 5.6.0
webpack: 3.11.0
```

**Comment by AndrewSouthpaw** [comment] 2018-03-15 19:09
I solved it by just going back to using bower for installing this plugin, which isn't the best, but it fixes the problem and I didn't have time to dive any deeper. 😞

**Comment by Arkni** [comment] 2018-03-19 11:37
@AndrewSouthpaw 

Could it be a cache problem with `yarn`?
I tested with `yarn` version `1.3.2` and everything works as expected.

**Comment by chithiraselvi** [comment] 2019-06-18 07:23
dfgdfg

**Comment by AndrewSouthpaw** [comment] 2019-06-21 17:42
Huh, interesting. I tried it again and now it seems to work. Maybe I hadn't cleaned out bower after adding it to yarn the last time? `¯\_(ツ)_/¯` It worked with `1.19.1`.

**Comment by ZenouskaMurphy** [comment] 2020-08-27 13:02
I am now getting this issue.
I have the following ...
"jquery": "^3.5.1",
"jquery-validation": "^1.19.2",

Are there any known issues with using the validate function with this Jquery version?

**Comment by dhara-thacker** [comment] 2021-02-15 12:41
> I am now getting this issue.
> I have the following ...
> "jquery": "^3.5.1",
> "jquery-validation": "^1.19.2",
> 
> Are there any known issues with using the validate function with this Jquery version?

I am also facing this issue with same versions. Any luck ? Were you able to make it working?

**Comment by AndrewSouthpaw** [comment] 2021-02-23 21:57
@dhara-thacker I'd suggest creating a simple repro repo to test it out. Usually in the process of simplifying the picture to get it reproducible, the issue reveals itself. 😄
