### ISSUE TITLE
The email is validated as true without .com at the end

### ISSUE THREAD

**Issue by rajibmishra-rgb** [jquery-validation/jquery-validation#2346] opened 2020-09-23 15:22 UTC
### Your environment
* version of `jquery-validate`:
* which browser and its version:

**Comment by RobJohnston** [comment] 2020-09-23 15:36
Duplicate of (most recently) https://github.com/jquery-validation/jquery-validation/issues/2321.

**Comment by staabm** [comment] 2020-09-23 15:50
thank you for taking the time to report a issue.

Unfortunately this topic was discussed already before. See the README.md for details:

> **IMPORTANT NOTE ABOUT EMAIL VALIDATION**. As of version 1.12.0 this plugin is using the same regular expression that the [HTML5 specification suggests for browsers to use](https://html.spec.whatwg.org/multipage/forms.html#valid-e-mail-address). We will follow their lead and use the same check. If you think the specification is wrong, please report the issue to them. If you have different requirements, consider [using a custom method](http://jqueryvalidation.org/jQuery.validator.addMethod/).
In case you need to adjust the built-in validation regular expression patterns, please [follow the documentation](http://jqueryvalidation.org/jQuery.validator.methods/).

**Closed** 2020-09-23 15:49 UTC
